### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by uwejan** [robertwayne/template-axum-solidjs-spa#17]
I think cache controll is not working;
`Cache-Control: no-cache`
While checking dev tools, for the loaded files, none of the css/js/svg got cached. Maybe am missing something here or there.

**Comment by robertwayne** [comment]
Hey, I see you closed this. Was this just a misconfiguration on your end?

I double-checked right now and I am seeing cache headers being set as expected, but I want to make sure I'm not missing anything.
